restic: ENC[AES256_GCM,data:n6qEN3sgPt7g0RsPJnpofg9y,iv:EUfl7/ahBcvLBILHjnxxIXmXpUFPXuHRrUPBnaFh1K0=,tag:FGi1MhS0EfNsuEVlgCQcYQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1s4vpg3n4heemgzsaqds8zd76z52jm2sp86tlahac3dqsszf5uvgsvafc94
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2VlVKNVVWbVdpY3pmcXh4
            Skp1N3NRbHY3VmJOUlRYL1BvY1lZTU9QTkR3CjUwWHFzZVZVY0RnMlcxaS9MWlgw
            WWxKUVk2MlRVc1FMQkllUmlidUF6NTgKLS0tIE5udzJ5Rk1USjNvbTNpYkQxZWJy
            SnVGMmUzVXJTU1dkUFdveWdDNDF2bkEKqhe84jVNZCsNcz9YtMfdILtiy4l+Df3Y
            MVkqFwgpjxw+OMGS+tRJOKvCnLQnzzv9b0DEa2A2lh0H5pLYTlnmPQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-22T17:35:14Z"
    mac: ENC[AES256_GCM,data:iaBHSOKVUoLgDmU1iijGuPBcbMbiYMky/JhwzMv7HPE/ZYRaiZs+spTY7Z1c6PRxD8/QF0luKYWIhVw+P45HmVoObGFcHHdXmiakDc6Lsm/boEQbR8etZAr9q7EnKDLHk/nGheROVv2DTsCptIvJ19hIwddW2Vsw/PxnO1IqYa4=,iv:7jHoe6pQBAUedpbj68yXiS/rzOtECXxj4NooFQPgttM=,tag:GFD+ZJUkWQcqdR/m0W962A==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
